# stratum_listen_port: the port that will be listening for incoming stratum traffic
# Note `:PORT` format is needed if not specifiying a specific ip range
stratum_port: :5555

# pyrin_address: address/port of the rpc server for pyrin, typically 13110
# For a list of public nodes, run `nslookup mainnet-dnsseed.daglabs-dev.com`
# ТУТ ПИШЕМ АДРЕС С НОДОЙ, порт не меняем
pyrin_address: localhost:17110

# min_share_diff: only accept shares of the specified difficulty (or higher) from
# the miner(s).  Higher values will reduce the number of shares submitted, thereby
# reducing network traffic and server load, while lower values will increase the
# number of shares submitted, thereby reducing the amount of time needed for
# accurate hashrate measurements
min_share_diff: 16

# block_wait_time: time to wait since last new block message from pyrin before
# manually requesting a new block
# block_wait_time: 500ms

# extranonce_size: size in bytes of extranonce, from 0 (no extranonce) to 3.
# With no extranonce (0), all clients will search through the same nonce-space,
# therefore performing duplicate work unless the miner(s) implement client
# side nonce randomizing.  More bytes allow for more clients with unique
# nonce-spaces (i.e. no overlapping work), but reduces the per client
# overall nonce-space (though with 1s block times, this shouldn't really
# be a concern).
# 1 byte = 256 clients, 2 bytes = 65536, 3 bytes = 16777216.
# extranonce_size: 0

# print_stats: if true will print stats to the console, false just workers
# joining/disconnecting, blocks found, and errors will be printed
print_stats: true

# log_to_file: if true logs will be written to a file local to the executable
log_to_file: true

